services:
  - type: web
    name: sylva-dashboard
    env: static
    buildCommand: cd dashboard && npm install && npm run build
    staticPublishPath: ./dashboard/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
